// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftibqgkubmirlbsuyrgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0aWJxZ2t1Ym1pcmxic3V5cmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODA0NjEsImV4cCI6MjA3MTM1NjQ2MX0.4HKaAtmR8vgQ7vhGI7jAG-HT9Yjt_0NRvFgtUPdgKzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});